### ISSUE TITLE
USB LED driver not found in Raspbian

### ISSUE THREAD

**Issue by DarylWM** [cliffano/buildlight#2]
The module doesn't work on Raspbian because /sys/bus/usb/drivers/usbled/ doesn't exist. Has anyone found a workaround?

**Comment by cliffano** [comment]
Hi @darylwm,

Is your Delcom build light a gen1 or gen2? You can tell from the PN (Part Number) at the bottom of the device.

The current buildlight code is based on gen1 because that's the only one I own.
If you have a gen2 device, I can come up with a usbhid-based driver off Delcom's spec, however I'll need your help to test it if you the time.

I also don't have a Raspbian, but AFAIK usbhid is available there.

**Comment by cliffano** [comment]
Closing this issue due for now. Usbhid implementation is there on master, will release a new version after gen2 testing. Feel free to re-open if anyone can help with testing.
